### ISSUE TITLE
Pull in latest changes from Spree repo

### ISSUE THREAD

**Issue by onedanshow** [Woodbolt-International/spree_wombat#3]
We haven't updated our gem since September. Nothing is broken, but I assume there are some changes we might benefit from.

This is a low priority item.

**Comment by AlessioRocco** [comment]
Spree have merged our changes https://github.com/spree/spree_wombat/pull/33 some time ago and we are using the `spree/spree_wombat` version for all our store. 
I advice to remove our version of this repo to not make confusion.
